// branches
Table "branches" {
  id bigint [primary key]
  is_default boolean [default: false, note: 'current/others']
  branch_name varchar(100) [not null]
  City varchar(100) [not null]
  State varchar(100) [not null]
  address varchar(255)
}

// user roles permissions
Table users {
  id bigint [primary key]
  branch_id bigint [not null]
  username varchar(50) [unique, not null]
  login_id varchar(50) [unique, not null]
  role_id bigint [not null]
  phone varchar(50)
  created_at timestamp
  updated_at timestamp
}

Table roles {
  id bigint [primary key]
  name varchar(50) [unique, not null]
  created_at timestamp
  updated_at timestamp

}

Table permissions {
  id bigint [primary key]
  role_id bigint [not null]
  name varchar(100) [not null]
  code varchar(100) [not null]
  created_at timestamp
  updated_at timestamp

}

Ref: users.branch_id > branches.id
Ref: users.role_id > roles.id
Ref: permissions.role_id > roles.id

// exchange rates
Table current_exchange_rates {
  id bigint [primary key]
  exchange_rate_history_id bigint [not null]
  created_at timestamp
  updated_at timestamp

}

Table exchange_rate_histories {
  id bigint [primary key]
  user_id bigint [not null]
  base_currency char(3) [not null, note: 'CNY']
  quote_currency char(3) [not null, note: 'MMK']
  rate decimal(18,6) [not null, note: '1 CNY = X MMK']
  status enum('active', 'inactive') [default: 'active']
  effective_from datetime [not null, note: 'When rate becomes active']
  effective_to datetime [note: 'NULL = current']
  created_at timestamp
  updated_at timestamp
}

Ref: current_exchange_rates.exchange_rate_history_id > exchange_rate_histories.id
Ref: exchange_rate_histories.user_id > users.id

//customers
Table "customers" {
  id bigint [primary key]
  is_default boolean [default: false, note: 'Walk-in / default customer']
  type enum('retail', 'wholesale') [default: 'retail']
  name varchar(100) [not null]
}

//customers
Table "customer_contacts" {
  id bigint [primary key]
  customer_id bigint [not null]
  phone varchar(50) [not null]
  nrc varchar(50)
  address varchar(255)
}

Ref: customers.id > customer_contacts.customer_id

// inventory

Table products {
  id bigint [primary key]
  sku varchar(50) [unique, not null]
  barcode varchar(50) [unique, note: 'EAN / UPC / QR']

  name varchar(100) [not null]
  description varchar(255)

  retail_price decimal(18,2) [not null]
  wholesale_price decimal(18,2)
  
  created_at timestamp
  updated_at timestamp
}



//Supplier
Table suppliers {
  id bigint [primary key]
  supplier_name varchar(100) [not null]
  contact_name varchar(100)
  phone varchar(20)
  email varchar(100)

  created_at timestamp
}

Table purchase_orders {
  id bigint [primary key]
  supplier_id bigint [not null]
  order_date date [not null]
  total_amount decimal(18,2)

  created_at timestamp
}

Table purchase_order_items {
  id bigint [primary key]

  purchase_order_id bigint [not null]
  product_id bigint [not null]

  quantity int [not null]
  unit_cost decimal(18,2) [not null]

  created_at timestamp
}

Table inventory_batches {
  id bigint [primary key]

  product_id bigint [not null]
  branch_id bigint [not null]
  purchase_order_item_id bigint [not null]

  cost_price decimal(18,2) [not null]

  quantity_received int [not null]
  quantity_remaining int [not null]

  received_at datetime [not null]
  expire_date date

  created_at timestamp

  indexes {
    (product_id, branch_id, received_at)
  }
}

Table pos_sales {
  id bigint [primary key]
  branch_id bigint [not null]
  customer_id bigint

  total_amount decimal(18,2) [not null]
  total_cost decimal(18,2) [not null]

  created_at timestamp
}

Table pos_sale_items {
  id bigint [primary key]

  pos_sale_id bigint [not null]
  product_id bigint [not null]

  quantity int [not null]
  unit_price decimal(18,2) [not null]

  created_at timestamp
}

Table inventory_fifo_logs {
  id bigint [primary key]

  pos_sale_item_id bigint [not null]
  inventory_batch_id bigint [not null]

  quantity int [not null]
  cost_price decimal(18,2) [not null]

  created_at timestamp
}

Ref: purchase_orders.supplier_id > suppliers.id
Ref: purchase_order_items.purchase_order_id > purchase_orders.id
Ref: purchase_order_items.product_id > products.id

Ref: inventory_batches.product_id > products.id
Ref: inventory_batches.purchase_order_item_id > purchase_order_items.id

Ref: pos_sale_items.pos_sale_id > pos_sales.id
Ref: pos_sale_items.product_id > products.id

Ref: inventory_fifo_logs.pos_sale_item_id > pos_sale_items.id
Ref: inventory_fifo_logs.inventory_batch_id > inventory_batches.id


